### PR TITLE
Trying to get arm working on master

### PR DESCRIPTION
**Pull request by gohai**
Hey Wilm, altes Haus!

Also bis jetzt nicht wirklich, weil diese schreckliche shake Teil auf dem Pi nicht will. ([Issue](https://github.com/ndmitchell/shake/issues/282)) Aber wird schon, irgendwann..

Hoff du hast einen guten Sommer und viel Spass mit Cargo Crunch-Time.

Cheers

### CODE REVIEW

**Comment by gohai** [comment]
Kannst du bei shake auf linux vielleicht die gcc invocations mitloggen? Ich glaub damit haette ich es schneller am laufen als Haskell am Pi zu fixen ;)

**Comment by wirsing** [comment]
yo g, diese nachricht ist hier völlig untergegangen irgendwie. kann ich dir noch was helfen?

**Comment by gohai** [comment]
Hi @wirsing!

(Switching to English for the benefit of non-German speakers)

I ran into two hurdles getting processing-sound to compile on Raspbian (Debian armv6hf):
- the Haskell-based build system seems to require GHCi, which was unavailable on ARM up until very recently - might be easier hacking together a Makefile that does the same GCC  invocations rather than bootstrapping a Haskell compiler
- Methcla seems to have a run-time dependency on libc++ which isn't available as a package - how is this handled on x86 with processing-sound?

Thxthx

**Comment by wirsing** [comment]
helo! 

mmh, yeah. About the Haskell build system... That is all maintained by the methCla developers and I am not involved in that really. We got it to work on Windows though so maybe it'll do on arm as well .. 

As far as I know libc++ is not included in the x86 version. There should probably be a seperate config file for that in methcla, they might be not up to date there though. I made my own including pulse audio stuff, the config is pretty simple once you got the haskell compiler running. 

cheers!

**Comment by gohai** [comment]
@wirsing 

Could you perhaps document the steps needed to compile the methCla shared library to be used with processing-sound? Stefan was replying to my email about the libc++ dependency: _das kommt auf die plattform an, auf osx wird gegen libc++ dynamisch gelinkt, auf linux auch, nehme ich an._

There's definitely some effort required to simply get the Haskell build tool to run on the Pi (bootstrapping a recent Haskell compiler). If we'd also have to build LLVM and libc++, and ship libc++ shared libraries, I am not so sure that this makes so much sense..

(Would be a shame not to have synthesis on the Pi though!)

**Comment by wirsing** [comment]
hey @gohai 

check this configs i used the last time i compiled for linux:

BuildFlags.compilerFlags = ${BuilFlags.compilerFlags} -fPIC -std=gnu++11 
BuildFlags.linkerFlags = ${BuildFlags.linkerFlags} -L /usr/lib/x86_64-linux-gnu -lpulse-simple -lpulse -Wl,-rpath,/usr/local/lib
BuildFlags.defines = ${BuildFlags.defines} **LINUX_PULSE** 

I just tried again today and there seems to be an issue in Methcla, i just contacted Stefan.

**Comment by wirsing** [comment]
thanks for the makefile update!

**Pull request merged**
